/// Flutter icons TCUMyinfoIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TCUMyinfoIcon
///      fonts:
///       - asset: fonts/TCUMyinfoIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class TCUMyinfoIcon {
  TCUMyinfoIcon._();

  static const _kFontFam = 'TCUMyinfoIcon';

  static const IconData megaphone = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData login = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData info_circled = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cog_alt = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData wrench = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData tags = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData attach_file = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData table = const IconData(0xf0ce, fontFamily: _kFontFam);
  static const IconData doc_text = const IconData(0xf0f6, fontFamily: _kFontFam);
  static const IconData building = const IconData(0xf0f7, fontFamily: _kFontFam);
  static const IconData direction = const IconData(0xf124, fontFamily: _kFontFam);
  static const IconData doc_inv = const IconData(0xf15b, fontFamily: _kFontFam);
  static const IconData doc_text_inv = const IconData(0xf15c, fontFamily: _kFontFam);
  static const IconData bank = const IconData(0xf19c, fontFamily: _kFontFam);
  static const IconData building_filled = const IconData(0xf1ad, fontFamily: _kFontFam);
  static const IconData sliders = const IconData(0xf1de, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xf1ea, fontFamily: _kFontFam);
  static const IconData calendar_plus_o = const IconData(0xf271, fontFamily: _kFontFam);
  static const IconData calendar_minus_o = const IconData(0xf272, fontFamily: _kFontFam);
  static const IconData calendar_times_o = const IconData(0xf273, fontFamily: _kFontFam);
  static const IconData calendar_check_o = const IconData(0xf274, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
}
